/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package rsc;


import java.io.*;
import javax.swing.JOptionPane;

/**
 *
 * @author master
 */
public class rscfrm extends javax.swing.JFrame {

    /**
     * Creates new form rscfrm
     */
    public rscfrm() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel8 = new javax.swing.JLabel();
        cflutetype = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        wsz = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        dsz = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtFilePathName = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        blksz = new javax.swing.JLabel();
        createDxf = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jCmbBtm = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        btnBlkSz = new javax.swing.JButton();
        lsz = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        dimtype = new javax.swing.JComboBox<>();
        jCmbTop = new javax.swing.JComboBox<>();
        jLabel9 = new javax.swing.JLabel();
        jCheckBox1 = new javax.swing.JCheckBox();

        jLabel8.setText("jLabel8");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("RSC 020x FEFCO designs");

        cflutetype.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "B", "C", "E", "BC", "EB" }));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel4.setText("Flute:");

        wsz.setToolTipText("Width");

        jLabel5.setText("x");

        dsz.setToolTipText("Height");

        jLabel6.setText("x");

        txtFilePathName.setText("aRSC.dxf");
        txtFilePathName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtFilePathNameActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel7.setText("File Name:");

        blksz.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        blksz.setText("1up Blank Size:");

        createDxf.setText("Create DXF Drawing");
        createDxf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createDxfActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel1.setText("Dim Type:");

        jCmbBtm.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "0201 (OFOTB)", "0200 (Raw Edge)", "0202 (OFO)", "0203 (OFFO)", "0204 (AFM)", "0205 (IFM)", "0206 (IFM/OFFO)", "0209 (Short Flap)", "0209g (OFG)" }));
        jCmbBtm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCmbBtmActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel2.setText("Style:");

        btnBlkSz.setText("Calc Blank Size");
        btnBlkSz.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBlkSzActionPerformed(evt);
            }
        });

        lsz.setToolTipText("Length");
        lsz.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lszActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel3.setText("Pack Size:");

        dimtype.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "ID: Internal Dimensions", "BB: Bend to Bend", "OD: Outside Dimensions" }));
        dimtype.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dimtypeActionPerformed(evt);
            }
        });

        jCmbTop.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "0201 (OFOTB)", "0200 (Raw Edge)", "0202 (OFO)", "0203 (OFFO)", "0204 (AFM)", "0205 (IFM)", "0206 (IFM/OFFO)", "0209 (Short Flap)", "0209g (OFG)" }));
        jCmbTop.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCmbTopActionPerformed(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel9.setText("/");

        jCheckBox1.setText("Make in 2 Pieces");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lsz, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(wsz, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(dsz, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(dimtype, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(58, 58, 58))
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(blksz, javax.swing.GroupLayout.PREFERRED_SIZE, 524, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel1)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(cflutetype, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(118, 118, 118)
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jCmbTop, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jCmbBtm, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(95, Short.MAX_VALUE))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(129, 129, 129)
                .addComponent(createDxf, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnBlkSz, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(156, 156, 156))
            .addGroup(layout.createSequentialGroup()
                .addGap(164, 164, 164)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtFilePathName, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(59, 59, 59)
                .addComponent(jCheckBox1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(dimtype, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1)
                    .addComponent(lsz, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(wsz, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5)
                    .addComponent(dsz, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(cflutetype, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(jCmbTop, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9)
                    .addComponent(jCmbBtm, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtFilePathName, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7)
                    .addComponent(jCheckBox1))
                .addGap(30, 30, 30)
                .addComponent(blksz)
                .addGap(45, 45, 45)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnBlkSz, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(createDxf, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(40, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void createDxfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createDxfActionPerformed
//        this.getSizes();  // Get ID / OD sizes
    checkSizes();    
    String outputDxfData = "";

        drawRscCls oDxf = new drawRscCls();
oDxf.xabs = 0;
oDxf.yabs = 0;
oDxf.slot = 6;

oDxf.topStyle = (String) this.jCmbTop.getSelectedItem();
oDxf.btmStyle = (String) this.jCmbBtm.getSelectedItem();
oDxf.topAddSz = 0;
oDxf.btmAddSz = 0;

oDxf.dxf = "";

        oDxf.xabs = 0;
        oDxf.yabs = 0;
        oDxf.length = Double.parseDouble(lsz.getText());
        oDxf.width = Double.parseDouble(wsz.getText());
        oDxf.depth = Double.parseDouble(dsz.getText());
        oDxf.make2piece = this.jCheckBox1.isSelected();

        oDxf.flute = (String) cflutetype.getSelectedItem();
        oDxf.cutlay = "CUT";
        oDxf.crelay = "CREASE";
        oDxf.dxf = ""; // Output File's contents
        oDxf.dxfxmax = "0";
        oDxf.dxfymax = "0";

        oDxf.Xaxis = 1; // Direction of X axis +1 or -1
        oDxf.Yaxis = 1; // Direction of Y axis +1 or -1
        oDxf.allowanceSetup();

        outputDxfData = oDxf.drwRsc();

        String outputDir = ""; // "/home/tim/NetBeansProjects/T0427/src/t0427/"; // "../temp/";
        File f = new File(outputDir + txtFilePathName.getText());
        if(f.exists() && !f.isDirectory()) {
            f.delete();
        }
        String outputDxfFile = outputDir + txtFilePathName.getText(); // "testfilel.dxf"; // "/var/www/temp/testfilel.dxf";

        BufferedWriter writer = null; // Note outside try block
        try {
            //create a file
            File newDxfFile = new File(outputDxfFile);

            writer = new BufferedWriter(new FileWriter(newDxfFile));
            writer.write(outputDxfData);
            writer.flush();
        } catch (Exception e) {
            e.printStackTrace();
        } finally {
            try {
                // Close the writer regardless of what happens...
                writer.close();
            } catch (Exception e) {
            }
        }

        JOptionPane.showMessageDialog(null, "Saved: " + outputDxfFile);
    }//GEN-LAST:event_createDxfActionPerformed

    private void jCmbBtmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCmbBtmActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCmbBtmActionPerformed

    private void btnBlkSzActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBlkSzActionPerformed
    // Get Allowances
    checkSizes();
    drawRscCls oDxf = new drawRscCls();
    oDxf.xabs = 0;
    oDxf.yabs = 0;
    oDxf.slot = 6;
    oDxf.length = Double.parseDouble(lsz.getText());
    oDxf.width = Double.parseDouble(wsz.getText());
    oDxf.depth = Double.parseDouble(dsz.getText());
    oDxf.flute = (String) cflutetype.getSelectedItem();
    oDxf.make2piece = this.jCheckBox1.isSelected();
    
    oDxf.topStyle = (String) this.jCmbTop.getSelectedItem();
    oDxf.btmStyle = (String) this.jCmbBtm.getSelectedItem();
    oDxf.topAddSz = 0;
    oDxf.btmAddSz = 0;
        
    oDxf.allowanceSetup();
    String htmlCol = "black";
    String msg = "";
    if(oDxf.blks1 > 1640) {
      htmlCol = "red"; 
      msg = "*** 1st Way TOO BIG - Try swapping Sizes around ***";
    }
    if(oDxf.blkn2 > 2140) {
      htmlCol = "red"; 
      msg = "*** 2nd Way TOO BIG - Make in 2 Pieces***";
      jCheckBox1.setSelected(true);
    }
    this.blksz.setText("<HTML>Blank Size: <font color='" + htmlCol + "'>" + Double.toString(oDxf.blks1) + " X " + Double.toString(oDxf.blkn2) + "  " + msg + "</font></HTML>");
    }//GEN-LAST:event_btnBlkSzActionPerformed
  
  private void checkSizes() {
     if (Double.parseDouble(lsz.getText()) < Double.parseDouble(wsz.getText())) {
         JOptionPane.showMessageDialog(null, "Width > Length Size Error! \nTHIS WILL RESULT IN A CASE MAKE UP FAILURE\nSwap the Length and Width Sizes", "Size Error", JOptionPane.ERROR_MESSAGE);
     } 
  }

    private void lszActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lszActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_lszActionPerformed

    private void dimtypeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dimtypeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_dimtypeActionPerformed

    private void txtFilePathNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtFilePathNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtFilePathNameActionPerformed

    private void jCmbTopActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCmbTopActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCmbTopActionPerformed
  
  
  
    public void getSizes() {  
  } // getSizes
    
    

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(rscfrm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(rscfrm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(rscfrm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(rscfrm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new rscfrm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel blksz;
    private javax.swing.JButton btnBlkSz;
    private javax.swing.JComboBox<String> cflutetype;
    private javax.swing.JButton createDxf;
    private javax.swing.JComboBox<String> dimtype;
    private javax.swing.JTextField dsz;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JComboBox<String> jCmbBtm;
    private javax.swing.JComboBox<String> jCmbTop;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField lsz;
    private javax.swing.JTextField txtFilePathName;
    private javax.swing.JTextField wsz;
    // End of variables declaration//GEN-END:variables
}
